# Generated by Django 3.0.4 on 2020-05-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
